
name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest

    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore nuget packages
      run: nuget restore "Signal Performance Metrics.sln"

    - name: Build
      run: msbuild "Signal Perfromance Metrics/MOE.Common.csproj" /p:Configuration=Release

